repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: t3n
    url: https://storage.googleapis.com/t3n-helm-charts
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: plex
    url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages

helmDefaults:
  kubeContext: homelab

templates:
  local-chart: &local-chart
    namespace: homelab
    missingFileHandler: Debug
    values:
      - "./values/{{`{{ .Release.Name }}`}}.yaml"

  remote-chart: &remote-chart
    namespace: homelab
    values:
      - "./values/{{`{{ .Release.Name }}`}}.yaml"

releases:
  # The prometheus install will fail if there are any other previous prometheus
  # stuff installed. I had to do:
  #   kubectl delete ns prometheus-operator
  - name: kps
    chart: prometheus-community/kube-prometheus-stack
    version: ^48.3
    <<: *remote-chart

  - name: static
    chart: ./charts/static
    <<: *local-chart

  - name: bitcoind
    chart: ./charts/bitcoind
    <<: *local-chart

  - name: grafana
    chart: bitnami/grafana
    version: ^9.0
    <<: *remote-chart

  - name: home-assistant
    chart: ./charts/home-assistant
    <<: *local-chart

  - name: mosquitto
    chart: t3n/mosquitto
    version: ^2.4
    <<: *remote-chart

  - name: pihole
    chart: mojo2600/pihole
    version: ^2.18
    <<: *remote-chart

  - name: plex
    chart: plex/plex-media-server
    <<: *remote-chart

  - name: postgresql
    chart: bitnami/postgresql
    version: ^12.8
    <<: *remote-chart

  - name: traefik
    chart: traefik/traefik
    version: ^24.0
    <<: *remote-chart
