apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: {{ .Values.image }}
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        ports:
          - containerPort: 32400
            name: main
            protocol: TCP
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: main
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: main
        livenessProbe:
          tcpSocket:
            port: main
        env:
          - name: UMASK
            value: "2"
          - name: UMASK_SET
            value: "2"
          - name: S6_READ_ONLY_ROOT
            value: "1"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
          - name: TZ
            value: Europe/Tallinn
          - name: ADVERTISE_IP
            value: https://plex.urgas.eu
          - name: ALLOWED_NETWORKS
            value: 172.16.0.0/12,10.0.0.0/8,192.168.0.0/16
          - name: PLEX_CLAIM
            value: {{ .claimToken }}
          - name: PLEX_PREFERENCE_GDM
            value: GdmEnabled=0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /media
            name: media
            readOnly: true
          - mountPath: /shared
            name: shared
          - mountPath: /dev/shm
            name: shm
          - mountPath: /tmp
            name: temp
          - mountPath: /var/logs
            name: varlogs
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
        supplementalGroups:
          - 568
          - 44
          - 107
      volumes:
        - name: config
          hostPath:
            path: /mnt/ssd-storage/homelab/plex/config
        - hostPath:
            path: /mnt/hdd-storage/media
          name: media
        - emptyDir: {}
          name: shared
        - emptyDir:
            medium: Memory
          name: shm
        - emptyDir: {}
          name: temp
        - emptyDir: {}
          name: varlogs
