apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
  name: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  ports:
    - name: main
      port: 8123
      protocol: TCP
      targetPort: main
  type: ClusterIP
