services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.4.0
    container_name: prowlarr
    restart: unless-stopped
    environment:
      TZ: Europe/Tallinn
      PUID: "568"
      PGID: "568"
    volumes:
      - /mnt/ssd-storage/homelab/prowlarr/config:/config
    networks:
      - homelab

networks:
  homelab:
    external: true
